### ISSUE TITLE
プラクティス「ブログを作る」に記載されているインターンのブログを一つにまとめたフィードの表示がエラーになる

### ISSUE THREAD

**Issue by mayosuke** [fjordllc/interns#101]
http://256interns.com/feeds.atom

**Comment by poyopoyo0** [comment]
@mayosuke すみません、こちら、 #98 で報告済み、 #99 で修正中ですので、 close させて頂きます。
修正が master にmerge されるまで、しばらくお待ち下さい :bow:

**Comment by mayosuke** [comment]
うわーしょっぱなからすいませんm(__)m
了解しました。ありがとうございます。

**Comment by poyopoyo0** [comment]
@mayosuke いえいえ。他に何か不具合ありましたら、お気軽に issue に上げて下さいませー。

**Comment by poyopoyo0** [comment]
@mayosuke 「みんなのブログ」のフィード http://256interns.com/feeds.atom が読み取れるようになりました。ご確認頂ければと思いますー。

**Comment by mayosuke** [comment]
@poyopoyo0 見れました！ありがとうございました！

**Comment by poyopoyo0** [comment]
@mayosuke こちらこそ、ご確認ありがとうございます！
