### ISSUE TITLE
日報機能の仕様確認を行う

### ISSUE THREAD

**Issue by poyopoyo0** [fjordllc/interns#104]
@yasulab さんに「まずは日報機能の仕様の確認を取ってみては？」とご助言頂いたので、現段階で実装できている日報機能と、これから実装したい機能の仕様の確認を、こちらの issue でやらさせて頂ければと思います。

# 現在の進捗
- [x] 日報の CRUD 機能を実装する
- [x] 日報の一覧画面・個別画面で作成ユーザー名を表示させる
- [x] 日報の新規作成画面で、当日の日付と作成ユーザー名がフォームに自動入力されるようにする
- [x] 日報の投稿画面でエラーメッセージが表示されるようにする
- [x] 投稿の保存前に投稿画面から離脱しようとしたとき、警告メッセージが表示されるようにする
- [ ] 日報の作成ユーザーだけでなく、更新したユーザーの名前も保持したい
 * 最初、更新ユーザー column を作成して、そこに更新ユーザー id を格納しようと思っていたのですが、 @yasulab さんに「その仕様だと、最新の更新ユーザーしか保持できないし、一般的な実装の仕方で無いかも。履歴機能を実装するやり方にした方が一般的」とご助言頂いたので、履歴機能を実装するやり方にしてみようと思います。
 * ぱっと検索した感じでは、 `paper_trail` で履歴機能を、 `diffy` で diff 機能を追加できそう。
 * 追記： `paper_trail` での履歴機能は オーバースペックなので、 gem を使わず、 models への追加で処理できるようにした方がいいでしょう、と @yasulab さんから追加でご助言頂きました。
 * 追記： komagata さんに確認したところ、履歴については取り敢えず直近の diff のみ確認できる機能があればいいとのことでした。 practice については直近の diff が Slack に通知されるという機能が実装済みなので、この機能を流用してみたいと思います。
- [x] 日報のコピー機能を実装したい
- [x] Markdown に対応したい
- [x] コメント機能を実装したい
- [x] 日報を新規作成して保存する際、バリデーションエラーが出ると、それまで入力していた日報の本文が全てクリアされる、という不具合への対処。タイトルについては、バリデーションエラー後の画面にも引き継がれている。

**Comment by poyopoyo0** [comment]
取り敢えず、日報の CRUD 機能までは実装できています。
 * 一覧画面：
![スクリーンショット 2015-10-22 23.43.03.png (110.3 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/22/1480/8a3c27c3-4bc7-4036-b35a-8835d5ed0eef.png)
 * 日報の個別画面：
![スクリーンショット 2015-10-22 23.50.18.png (77.5 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/22/1480/438a05dd-1f8b-4070-b41f-57176594e5fd.png)
 * 日報を新規作成した直後の画面：
![スクリーンショット 2015-10-22 23.54.14.png (84.9 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/22/1480/a6b7c810-10d8-4129-b6fb-188c431690f7.png)
 * 日報を更新した直後の画面：
![スクリーンショット 2015-10-22 23.55.54.png (86.2 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/22/1480/a2a266be-cdb5-42da-bffe-42cc2d7100c9.png)
 * 日報を削除した直後の画面：
![スクリーンショット 2015-10-22 23.59.31.png (150.8 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/23/1480/dd732a25-8e65-4334-b06e-5f26d8d41fc0.png)

**Comment by poyopoyo0** [comment]
* 一覧画面
  * 日報の作成ユーザー名と、作成日時が表示されるようにしてあります。
  * 画像では更新ユーザー名として表示されているが、実際に表示されているのは作成ユーザー名です。
![スクリーンショット 2015-10-24 6.11.51.png (131.4 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/24/1480/22afcbda-781a-48ea-b3a7-7d9d7ae5c23d.png)
 * 個別画面
  * 日報の作成ユーザー名が表示されるようにした他、作成日時と更新日時が表示されるようにしてあります。
  * 画像では更新ユーザー名も表示されているが、実際に表示されているのは作成ユーザー名。
![スクリーンショット 2015-10-24 6.02.28.png (58.4 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/24/1480/a0bc0dcf-9559-4b3e-b539-82eabb3e1f8e.png)
 * 新規作成画面
  * 当日の日付と作成ユーザー名が、フォームに自動入力されるようにしました。
![スクリーンショット 2015-10-24 6.05.22.png (49.1 kB)](https://img.esa.io/uploads/production/attachments/79/2015/10/24/1480/0aee3d02-2008-4f1c-b0d2-1e006ec3370b.png)

**Comment by komagata** [comment]
@poyopoyo0 急ぎなのでとりあえずCRUDがPRで確認できればよいですー

**Comment by komagata** [comment]
@poyopoyo0 

> Markdown への対応は、また後ほどでも大丈夫でしょうか…？

後で良いです。

数日前にesaのユーザー数が上限になってしまいまって日報に入れない人が出ている状態です。
なのでデータ移行を優先させたいです。

**Comment by poyopoyo0** [comment]
@komagata 了解しました。いま、 HoundCI に怒られてしまっているところの修正に苦戦しているのですが、対応できましたら #88 でご連絡させて頂きます！

**Comment by komagata** [comment]
@poyopoyo0 了解ですー

**Comment by yasulab** [comment]
その場で聞いてパッと答えただけなので、コンテキストを誤解しているかもしれませんが、何かのご参考になっていれば幸いです :bow:

**Comment by poyopoyo0** [comment]
こちらこそ、昨日は大変お世話になりました :bow: 
@yasulab さんにご指摘頂いたように、仕様確認が必要な段階だったようです。
取り急ぎ、 CRUD 機能のみを実装して、その他の機能は徐々に実装していく…、という方向のようなので、履歴機能などは追々実装していこうと思います。

この度は本当にありがとうございました！

**Comment by machida** [comment]
おお、 @yasulab さん君臨！！@poyopoyo0 さんが、お世話になりました。ありがとうございます :sparkles:
今後も coedo.rb にインターンの方々がお世話になるかと思います。よろしくお願いします。

**Comment by yasulab** [comment]
こちらこそよろしくお願いします! :)

**Comment by komagata** [comment]
@poyopoyo0 これIn ProgressにありますがIssueとしてどういうステータスでしょう？

**Comment by poyopoyo0** [comment]
@komagata 
issue 開きっぱなしにしてしまっていてすみません :sweat_drops: 
こちらは、日報機能の進捗のメモ代わりに [description](https://github.com/fjordllc/interns/issues/104#issue-129104479) を使用していました。

直近の diff の表示がまだなので、 issue を開き続けていましたが、取り敢えず日報機能の master への merge は完了しましたし、こちらは close してしまった方がよろしいですかね…？

**Comment by komagata** [comment]
@poyopoyo0 Issueの内容が曖昧・粒度が大きすぎるので終わってないものを明確な別Issueとして切り出してこのIssueはCloseして良いと思います。

**Comment by poyopoyo0** [comment]
@komagata 
了解です！ 未実装の機能については #113 に上げておきました。
こちらの issue は close させて頂きます。
