### ISSUE TITLE
日報とプラクティスを紐付けたい

### ISSUE THREAD

**Issue by machida** [fjordllc/interns#107]
日報とプラクティスが紐付いてて、ここに表示されると嬉しい。
![image](https://cloud.githubusercontent.com/assets/168265/13166247/d6e4b662-d708-11e5-91d7-143ce815c080.png)
多くなってしまった場合、最新10件だけ出して、全部見る、みたいなリンクを表示したい。
いずれは役立った機能みたいなのを付けて、評価の高い順に並ぶとかほしい。

ここにボタンを置いて、日報が書けるとよさそう。
![image](https://cloud.githubusercontent.com/assets/168265/13166383/9343c9d2-d70a-11e5-9db6-52034700d820.png)
# 現在の進捗
- [x] フォーム画面の作成
- [x] 学習日報のタイトル入力欄に、自動で  _学習週/<カテゴリ名>/<プラクティス名>/<日付>/<ユーザー名>_ が表示されるようにしたい
- [x] プラクティスと学習日報との、多対多による連携の実装
- [x] 学習日報を削除するとき、中間テーブル `PracticeReport` のレコードも一緒に削除したい
- [x] 学習日報の個別画面で、関連するプラクティスを表示させる
- [ ] 学習日報投稿時にエラーメッセージが出ると、プラクティスとの連携が失われてしまうことへの対応
- [ ] コピー機能を用いてコピーした学習日報が、プラクティスと連携されていないことへの対応
- [ ] 作成済みの学習日報で、連携しているプラクティスを後から編集できるようにしたい

**Comment by machida** [comment]
- 作業日報と学習日報を分けたい
- 学習日報はプラクティスと紐付けたい

**Comment by poyopoyo0** [comment]
https://github.com/fjordllc/interns/pull/106#issuecomment-186041889 と https://github.com/fjordllc/interns/pull/106#issuecomment-186042764 で @machida さんにご説明頂いた内容を [description](https://github.com/fjordllc/interns/issues/107#issue-132077954) に反映させました。ご自由に修正頂ければと思います。
