### ISSUE TITLE
日報に直近の diff 表示を実装したい

### ISSUE THREAD

**Issue by poyopoyo0** [fjordllc/interns#113]
practice については直近の diff が Slack に通知されるという機能が実装済みなので、この機能を流用することで実装できそう。

**Comment by hattori6789** [comment]
@komagata 直近のDiffの表示というのは、以下のようなイメージでしょうか？

![2017-03-27 13 18 57](https://cloud.githubusercontent.com/assets/12538161/24340866/7af9cd90-12f0-11e7-95a6-e3753d99217b.png)

**Comment by hattori6789** [comment]
以下のようなイメージしてます。

![2017-03-27 13 18 57](https://cloud.githubusercontent.com/assets/12538161/24340866/7af9cd90-12f0-11e7-95a6-e3753d99217b.png)

**Comment by komagata** [comment]
@hattori6789 よくわからないですね。一旦Closeしちゃいましょう。
