### ISSUE TITLE
Pry コンソール上で step や next のコマンドを打ち込むとエラーになる

### ISSUE THREAD

**Issue by poyopoyo0** [fjordllc/interns#114]
`binding.pry` を書き込んだ後 Pry コンソールを立ち上げて `step` と打ち込むと
```
NameError: undefined local variable or method `step' for #<ReportsController:0x007fc835a0a280>
from (pry):4:in `index'
```
のようにエラー表示されて、 `step` コマンドを実行できない。
また、同様に `next` を打ち込んだ場合は
```
SyntaxError: (eval):2: Can't escape from eval with next
```
とエラー表示されてしまい、 `next` コマンドを実行できない

![2016-03-07 22 04 27](https://cloud.githubusercontent.com/assets/10114122/13570241/a18264e6-e4b0-11e5-8f6a-e46f36334ab0.png)

gem の中の動きも見えるように、 Pry コンソールで `step` コマンドと `next` コマンドを使えるようにしたい。

**Comment by ka2n** [comment]
Use with `pry-byebybug` https://github.com/deivid-rodriguez/pry-byebug

**Comment by komagata** [comment]
バグじゃないと思うのでCloseしましす。
