### ISSUE TITLE
日報の本文を検索する機能を実装する

### ISSUE THREAD

**Issue by hattori6789** [fjordllc/interns#123]
# ToDo
- [x] 検索フォームの設置
- [x] 検索結果一覧画面を作成
- [x] 入力されたキーワードからクエリを作成し、データベースから値を取得
- [x] 検索フォームのデザイン

**Comment by hattori6789** [comment]
@komagata @machida やってみたいです🙋

**Comment by komagata** [comment]
@hattori6789 お願いします。

**Comment by hattori6789** [comment]
# サーチフォームの位置案
## 参考画像
![default](https://cloud.githubusercontent.com/assets/12538161/20047210/45a7b58a-a4f5-11e6-92f4-721336c92a1b.png)

## 補足情報

* `page-header`ではなく`global-nav`に設置したい
 * `reports`画面に行かないと検索出来ないことが不便なため
 * 今後、`reports`画面以外にも、日報を書くボタンが設置されそうなので、サーチフォームを`reports`画面に置くことにこだわらなくて良さそう
 * 参考画像のようにサーチフォームに 日報の検索フォームだと分かる情報を添える`Search Reports`、`日報 検索`など
* global-navのlinksが増えるならどうする？
 * kowabanaと同様に、アイコンをクリック => サーチフォームが現れるようにする？

**Comment by hattori6789** [comment]
# 検索結果画面イメージ

## 参考画像
![256interns_](https://cloud.githubusercontent.com/assets/12538161/20050179/0d31103c-a50b-11e6-8ddc-455e854673fd.png)

## 補足

### 画面全体
* reports画面を参考にしています

### 1. について
* 検索ワードが表示されている

### 2. について
* reports画面では、`日報`と表示されていたものを、`'検索ワード'の検索結果`と表示する
* 検索フォームには、検索ワードを表示する

### 3. について
* internsの`description`のデータを表示する

**Comment by komagata** [comment]
@hattori6789 デザインは @machida さんに確認すると良いかもです。

**Comment by hattori6789** [comment]
@komagata かしこまりました！
@machida ご都合の宜しい時に、ご確認頂けたら嬉しいです！

**Comment by hattori6789** [comment]
# 機能リスト

1. global-nav__containerに検索アイコンを表示
- 虫眼鏡アイコンが押された際の動作
- 検索ボタンが押された際の動作
- データの取得
- 検索結果の一覧画面を表示

# 機能詳細

## global-nav__containerに検索アイコンを表示

1. 虫眼鏡アイコン
    *  `<div class="global-nav__container"></div>` に虫眼鏡アイコンを表示

## 虫眼鏡アイコンが押された際の動作

1. 虫眼鏡アイコンは
    * バックグラウンドカラーを変更
    * header-search__container containerを表示（hiddenステータスを解除）

* 検索フォームは
    * 補足メッセージ（キーワードを入力）の入った検索フォームを表示
    * 検索ボタンを表示
    * 入力待ちにしてフォーカスを当てる（カーソルが点滅する）

## 検索ボタンが押された際の動作

1. 検索ボタンは
    * 押されたと分かる動きをする（coffee.js？）
    * データベースにクエリを送り、値を保持する

* 画面は
    * search（検索結果一覧）画面へ遷移する
    * （怖話では、`http://kowabana.jp/search?utf8=✔︎&word=<キーワード>`へ移動）
    
* 入力された値は
    * データベースへの処理要求に使われる
    * 検索結果一覧画面で使えるように保持される

## データの取得

* `<div class="reports-item”></div>`に表示するデータリスト

	* reportsテーブルからデータを取得
	    * 日報タイトル  （"title" varchar(255) NOT NULL）
	    * 日付（"updated_at" datetime）
	    * 下にdescriptionを（3, 4行）表示（"description" text）

	* commentsテーブルから取得？
		*  コメント件数

	* Gravatarから表示？
		* ユーザーアイコン

## 検索結果の一覧画面を表示

* 何かのViewを再利用して、部分的に値を代入して表示？
    * 検索された文章の一部を`<div class="reports-item”>`に表示
        * `<div class="post-item__content">`？を設置する
    *  `<h2 class="page-header__title"> 検索キーワード の検索結果</h2>`と表示
