### ISSUE TITLE
日報一覧・ユーザー一覧にページネーション機能を追加したい

### ISSUE THREAD

**Issue by hattori6789** [fjordllc/interns#139]
日報一覧ページ・ユーザー一覧ページが縦に長い為

![2016-12-06 16 31 40](https://cloud.githubusercontent.com/assets/12538161/20916922/cae44c70-bbd1-11e6-89b8-5a9348be5420.png)

**Comment by hattori6789** [comment]
@komagata @machida やりたいです🙋

**Comment by hattori6789** [comment]
kowabanaを参考にしながら、[kaminari](https://github.com/amatsuda/kaminari#configuring-default-per_page-value-for-each-model)を使ってみるつもりです。

**Comment by komagata** [comment]
@hattori6789 お願いします。

**Comment by hattori6789** [comment]
@komagata かしこまりました😄
> kowabanaはauto pagerになってるので参考にしないほうがいいと思います。
