### ISSUE TITLE
ユーザー一覧の「作業週」「学習週」のタブにアクセスできない

### ISSUE THREAD

**Issue by snagasawa** [fjordllc/interns#143]
256Internsのユーザー一覧の「作業週」「学習週」にアクセスすると「We're sorry, but something went wrong.」と表示されてしまいます。

**Comment by hattori6789** [comment]
@komagata 本件のIssueと内容が重複していると思ったため、https://github.com/fjordllc/interns/issues/152 をCloseしました。
