### ISSUE TITLE
二語以上の検索が出来ない

### ISSUE THREAD

**Issue by hattori6789** [fjordllc/interns#177]
![2017-03-27 13 45 15](https://cloud.githubusercontent.com/assets/12538161/24341294/a9bd0504-12f3-11e7-9f9e-9d5433b678d7.png)

**Comment by Hirotacas** [comment]
@hattori6789 このIssuesに挑戦してもよろしいでしょうか？

**Comment by hattori6789** [comment]
@Hirotacas お願いします！

**Comment by Hirotacas** [comment]
@hattori6789 ありがとうございます😄　頑張ってみます。💪
