### ISSUE TITLE
サインイン状態を永続化したい

### ISSUE THREAD

**Issue by komagata** [fjordllc/interns#178]
多分ブラウザ閉じるとログアウト

**Comment by hattori6789** [comment]
@komagata ブラウザを閉じてもサインイン状態を維持できそうです。
（PC）SafariとChromeで確認してみました。

**Comment by komagata** [comment]
@hattori6789 スマホはどうでしょう？

**Comment by hattori6789** [comment]
@komagata iPhone6sでもサインイン状態を維持出来ているようです。
SafariとChromeそれぞれのブラウザで、タブを閉じた後にバックグラウンドから消して、状態確認しました。

**Comment by komagata** [comment]
@hattori6789 なんでだろう？iPhoneのSlackからリンクを踏むといつもログアウトしてるんですよね。
sorceryのログイン期間がどのくらいの設定になってるのか確認してみてくださいー

**Comment by hattori6789** [comment]
@komagata ログイン期間の確認は`user.remember_me_for = 256.weeks`の箇所で合っていますか？
[interns/sorcery.rb · fjordllc/interns](https://github.com/fjordllc/interns/blob/bc0e646bc5bcaea556d09d2c487bfca83ad91aa0/config/initializers/sorcery.rb#L39)

`session timeout`とかも、defaultのままでした。

**Comment by komagata** [comment]
@hattori6789 

> 箇所で合っていますか？
そうだと思います。

256internsってそもそも「ログイン状態を保持する」的なチェックボックスが無い気がしますね。

**Comment by hattori6789** [comment]
@komagata 作業週にログイン状態維持のチェックボックスつけます！

**Comment by hattori6789** [comment]
@komagata ChromeとSafariなど、複数のブラウザでログインしている時に起きますか？
> iPhoneのSlackからリンクを踏むといつもログアウトしてるんですよね。

**Comment by komagata** [comment]
@hattori6789 いえ、iOSのMobileSafariだけを使っています。

**Comment by hattori6789** [comment]
@komagata そうでしたかー。ChromeもSafariそれぞれSlackのリンクからアクセスしてみたのですが、ログイン状態を維持出来ていました。PCでもiPhoneでも維持出来ていることを確認しました。

しかし、複数のブラウザでログインし、ブラウザを閉じた場合、最後にログインしたブラウザしかログイン状態が維持されていないみたいでした。

例
PCのSafariでログイン => PCのChromeでログイン => Safariブラウザを終了し再起動 => Safariで再度ログインを求められる

**Comment by hattori6789** [comment]
今回のIssueの内容は一つのブラウザでのケースなのですが、上記に書いた複数のブラウザのログイン状態が維持出来ない件はデフォルト設定でした。https://github.com/NoamB/sorcery/pull/690

**Comment by komagata** [comment]
@hattori6789 なるほど。
では複数ブラウザでログイン維持が可能になる設定お願いしますー。

**Comment by hattori6789** [comment]
@komagata わかりました！ログイン画面にサインイン状態維持のチェックボックスを作成するIssueを立て、複数ブラウザでログイン可能にする条件を作業内容に含めます。

**Comment by hattori6789** [comment]
Issue作成しました。#179

**Comment by komagata** [comment]
ありがとうございます。
