### ISSUE TITLE
インターン用のテキストでリンク切れのところを調査して修正する。また古い情報を新しい情報にする。

### ISSUE THREAD

**Issue by MiwaMurata** [fjordllc/interns#183]

**Comment by MiwaMurata** [comment]
現在調査中です

**Comment by Hirotacas** [comment]
@komagata @machida 現在リンク切れ及びその修正を行っています。
リンク先が存在していても情報が古い場合は新しい情報に置き換えてもよろしいでしょうか？

**Comment by Hirotacas** [comment]
### プラクティス内容: Mac OS X - PC性能の見方を知る -
#### 修正内容:
- CPUが分かる　のリンクが移動していたので移動先を設定しました。
- メモリが分かる　のリンクが移動していたので移動先を設定しました。
- HDDが分かる　のリンクが移動していたので移動先を設定しました。移動先のページにはSSDの内容も書かれていたので「HDDとSSDが分かる」に変更しました。
### 参考に
- Macのシリアル番号を確認する方法 を追加しました。
- iMac のモデルを識別する方法 を追加しました。
- Mac mini のモデルを識別する方法 を追加しました。
- Mac Pro のモデルを識別する方法 を追加しました。

**Comment by Hirotacas** [comment]
### プラクティス内容: macOS - macOSをクリーンインストールする -
#### 修正内容:
- Macのバックアップ方法　の公式リンクを追加しました。
- Macのアップデート方法　の公式リンクを追加しました。
- Macのクリーンインストール方法　の公式リンクを追加しました。

**Comment by komagata** [comment]
@Hirotacas こちら完了でしょうか？

**Comment by Hirotacas** [comment]
@komagata　はい。#182 は完了で大丈夫です。
プラクティス全体を見たら結構リンク切れがあるので修正しています。

**Comment by Hirotacas** [comment]
@komagata 「インターン用のテキストでリンク切れのところを調査して修正する。また古い情報を新しい情報にする」が完了しました。
リンク切れの主な原因はリンク先のURLが変わっていたものが多く記事自体は残っていたのでタイトルをググって見つけてきました。
また、古い情報だとつまずきそうな箇所は新しい情報を追加しました。
リンク切れで唯一わからない箇所が一つあってそれは「webアプリ、サービスを作る」の「30秒で顧客や投資家を説得する効果的なエレベーターピッチのコツ」です。
ご確認頂ければ幸いです。
