### ISSUE TITLE
wiki、日報、コメント、プラクティスに画像を貼る機能が欲しい

### ISSUE THREAD

**Issue by machida** [fjordllc/interns#211]

**Comment by sanfrecce-osaka** [comment]
@machida 現状でもマークダウンで画像を挿入することはできるのですが、この機能はそれとは別の、例えばコピー＆ペーストで貼り付けることを可能にするということでしょうか？

**Comment by machida** [comment]
@sanfrecce-osaka いえ、今ある機能を指してます。このissueは7月に作ったものなので、一通りできるようにしてもらったのでcloseします！
