### ISSUE TITLE
チュートリアル個別ページに完了ボタンを出したい

### ISSUE THREAD

**Issue by machida** [fjordllc/interns#220]

**Comment by Hirotacas** [comment]
@machida このIssuesやってみてもよろしいでしょうか？

**Comment by komagata** [comment]
@Hirotacas お願いします！

**Comment by Hirotacas** [comment]
@komagata ありがとうございます!!

**Comment by Hirotacas** [comment]
@komagata @machida  現在issueの「プラクティス個別ページに完了ボタンを出したい」 をやっています。この完了ボタンの処理はjsで書いた方がよろしいでしょうか？
