### ISSUE TITLE
rubocopの指摘点を修正する

### ISSUE THREAD

**Issue by komagata** [fjordllc/interns#232]
‘を”に修正するとかいろいろ。

**Comment by midoriasi** [comment]
こちら、できそうなのでアサインしてもよろしいでしょうか？

**Comment by midoriasi** [comment]
@komagata こちらできそうなのでアサインしてもよろしいでしょうか？

**Comment by komagata** [comment]
@midoriasi 「アサインする」ってのはやっていいですか的な意味ですか？
だとすればお願いします。
