### ISSUE TITLE
確認有りプラクティスでは完了をメンターにお願い出来るようにする。

### ISSUE THREAD

**Issue by Hirotacas** [fjordllc/interns#243]
## 仕様

[![https://gyazo.com/e1d301efcca0f02da7a518c90d1d0508](https://i.gyazo.com/e1d301efcca0f02da7a518c90d1d0508.jpg)](https://gyazo.com/e1d301efcca0f02da7a518c90d1d0508)

- [x] 一般ユーザーはプラクティスを完了できなくする。（管理者はできる）
- [x] 成果物のアップロードフォームをプラクティスに付ける
  - [x] テキストエリアがあり、そこにメッセージを書ける。「確認宜しくお願いします。」とか書くイメージ。（成果物がURLの場合はそこに書く）
  - [x] 画像ファイルかzipファイルのみアップできる。
- [x] 成果物のアップロードはメッセージ付きでSlackに流れる。
- [x] 成果物はアップロード者本人と管理者しか見えない。

**Comment by komagata** [comment]
@Hirotacas 仕様書いておきました。

**Comment by Hirotacas** [comment]
@komagata すごい‼️ ありがとうございます🙏
