### ISSUE TITLE
プロフィール画面の表示が崩れている

### ISSUE THREAD

**Issue by sanfrecce-osaka** [fjordllc/interns#255]
- 発生画面
プロフィール画面：http://256interns.com/users/id
- 発生現象
プロフィール画面の表示が崩れている。
具体的にはログインネームとSNSのアイコン。
カラムからあふれてしまっている。
またこれに付随してブログとフィードのアイコンがクリックできない。
確認した環境はMacBookProの13インチ、ブラウザのサイズは1268px。
ブラウザを最大化（1280px）しても同様の発生する。

参考画像
[https://gyazo.com/ba20225bba27a41881bb4776ff173371](url)

**Comment by machida** [comment]
@sanfrecce-osaka 多分直ってるはず
