### ISSUE TITLE
QandAの編集画面がずれる

### ISSUE THREAD

**Issue by chamao** [fjordllc/interns#282]

**Comment by chamao** [comment]
![intern.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d71241f0f21d00120da3c8/125516c66e82c728ace21e0d46e19a8e26908debc3abaf51ab57f5973d047d317c52f27925d2b27cef1a28035b0d48fd41580917fdfedd22b4aa2e32db025fb28c341521842f1bbeb98b15be04bb218d4786b2bb8d49c0ea2f68.png)

こんな感じで。
ブラウザはFireFoxにて確認

**Comment by machida** [comment]
@chamao これ多分直したと思うので確認お願いしますー！

**Comment by chamao** [comment]
@machida 
確認しました。大丈夫でした！
大変遅れて申し訳ありません（メールに全く気づきませんでした。。。）。
