### ISSUE TITLE
pageの編集ができなくなりました

### ISSUE THREAD

**Issue by machida** [fjordllc/interns#336]
pages のshowでタイトルに `[` と `]` どちらかが入ってると `/edit` でエラーが起きます。

pages/[]xxxxxxx/edit にいけなくなります。

`bad URI(is not URI?):`

![image](https://user-images.githubusercontent.com/168265/35715143-13ea2306-0814-11e8-9c8a-17850b86a49b.png)

**Comment by machida** [comment]
@komagata こちらお願いしますー

**Comment by komagata** [comment]
@machida 修正しました。

**Comment by machida** [comment]
@komagata ありがとうございます！！
