### ISSUE TITLE
申し込みフォームの項目の追加

### ISSUE THREAD

**Issue by machida** [fjordllc/interns#68]
いつまでに何ができるようになるのが目的なのかを具体的に書くようにする。

いつまでに は、年月日を入力

何ができる は、就職、転職、起業、サービス立ちあげ、その他自由記入欄にする

この項目を見て、要望・目的とインターンの仕組みがマッチしているか、設定した期間が現実的であるか、を確認し、マッチしている人のみリモートも受け入れるようにする。
設定した期間が現実的でない場合は、もう一度考え直してもらう。

また、運営側はこの項目を今後学習を進めていく上でこの要望・目的に向かってちゃんと学習ができているかを確認する指標にする。

**Comment by komagata** [comment]
@HISAS これお願いします。

やるまえに @machida さんに詳細聞いてください。

**Comment by HISAS** [comment]
@machida 追加する項目について詳細をお願いします。

**Comment by machida** [comment]
@HISAS 

![image](https://cloud.githubusercontent.com/assets/168265/23599031/c36f7a4a-0281-11e7-92e2-2b19269bc8da.png)

こんな感じでお願いします 🙏
