### ISSUE TITLE
しばらく作業していない人への通知メールが欲しい

### ISSUE THREAD

**Issue by komagata** [fjordllc/interns#82]

**Comment by s3-asano** [comment]
日報とユーザ一覧情報をマッチングして、リスト化しようと思いますがどうでしょうか。情報はRubyでクローリングし、定期的に自動的にリストアウトできるように考えたいと思います。その方向で良いようでしたら、作業週の作業として取り組もうと思います。

**Comment by komagata** [comment]
@s3-asano いいですね。
できれば interns のアプリないのプログラムとして作成して、HerokuのSchedulerで動かしたいですね。

**Comment by s3-asano** [comment]
@komagata 確認ありがとうございます。検討してみます。初めてなので行き詰まった時は相談させてください。宜しくお願いします。

**Comment by komagata** [comment]
@s3-asano 作業の進捗や報告はこちら(github)の方でお願いします。
なぜなら、作業のログが一つのところでソースとセットで確認できることであとから見た人でも理解できて引き継ぎなどもしやすいからです。

**Comment by s3-asano** [comment]
@komagata 了解です。すみませんでした。

**Comment by s3-asano** [comment]
（2/4日報で報告済みですが）情報の一元管理の意味合いで、現対応状況について以下、ポイントのみ転載します。
First Stepとして、単体で以下の動作ができるようにしました。
・ローカルでプログラムを起動し、インターンのページから情報を取得する。
・取得した情報をグーグルスプレッドシートにアップロードすれば情報一覧が生成。
2/4実施した情報は以下にあります。
https://docs.google.com/spreadsheets/d/1q0098jIgP15DhEfVLZlk-9D4eu3h1jG2cH52Ti2EWyY/edit#gid=338203074

なお、この時点のコードは以下。
https://github.com/s3-asano/fjintrn/blob/master/intern_activity_report.rb

次回作業日からinterns のアプリ内のプログラムとして作成して、HerokuのSchedulerで動かすように対応します。

**Comment by komagata** [comment]
@s3-asano ありがとうございます。了解です。

**Comment by s3-asano** [comment]
@komagata 単体ローカルで動作するものが前回作業週にできたので、「interns のアプリ内のプログラムとして作成」を行おうと思っています。internsのアプリ内プログラム作成する際に参考になる情報ページがありましたら教えてもらえませんでしょうか。アバウトな情報、URLで結構です。いろいろ見てはいるのですが。

**Comment by s3-asano** [comment]
@komagata Wikiに記載の開発フローを参考に、ローカル環境を構築して作業をすれば良いでしょうか。また、インターンのリポジトリは、fjordllc/interns で良いでしょうか。初歩的な確認で恐縮ですが、念の為、確認迄。

**Comment by s3-asano** [comment]
@komagata 調べて、進め方だいたいわかりました。
実装イメージ確認させてください。以下でいかがでしょうか。
・実装場所：ユーザ一覧のページ(users)
・naviメニュ：「アドバイザ」の隣あたりに「活動状況」
・表示内容：「活動状況表示更新」のボタンをつけ、それをクリックすると、前回報告のシートのような内容（以下再掲）を表示。
https://docs.google.com/spreadsheets/d/1q0098jIgP15DhEfVLZlk-9D4eu3h1jG2cH52Ti2EWyY/edit#gid=338203074

**Comment by komagata** [comment]
@s3-asano それでお願いします。

早い段階でWIPのPull Requestをいただければ方向性が見えやすくなります。

**Comment by s3-asano** [comment]
@komagata ありがとうございます。了解です。引き続き宜しくお願いします。

**Comment by s3-asano** [comment]
@komagata 前回ストップしていたローカル環境の構築はお陰様で終了し、ソース等確認しているところです。基本的なことを聞いてすみませんが、サインアップはどうすればいいのでしょうか？

**Comment by komagata** [comment]
@s3-asano seed（初期データ）は下記で設定しています。
https://github.com/fjordllc/interns/blob/master/db/fixtures/users.yml

id: komagata
password: testtest

というユーザーがいるのでそちらを使うか、DBを変更して好きなユーザーを作ってください。

**Comment by s3-asano** [comment]
ありがとうございます！私も今、気づいて見ていたとこでした。お手数をおかけしました。新婚旅行楽しんできてください！
